sonar.projectKey=dnd5e-character-sheet
sonar.projectName=DnD 5e Character Sheet
sonar.projectVersion=0.2.0

sonar.sources=src
sonar.exclusions=node_modules/**,.next/**,public/**,scripts/**
sonar.sourceEncoding=UTF-8
